---
version: 2
updates:
  # Enable version updates for maven
  - package-ecosystem: "maven"
    directory: "/"
    # Check the maven registry for updates every day (weekdays)
    schedule:
      interval: "daily"
      # Check for npm updates on a daily basis
      time: "01:42"
      timezone: "Europe/Berlin"
    # Disable rebasing for dependabot pull requests
    rebase-strategy: "disabled"
    target-branch: "main"
    open-pull-requests-limit: 50
    groups:
      utils:
        patterns:
          - "org.jadice.util:*"
      dss:
        patterns:
          - "eu.europa.ec.joinup.sd-dss:*"
      test:
        patterns:
          - "org.junit.jupiter:*"
          - "org.hamcrest:*"
      log:
        patterns:
          - "org.apache.logging.log4j:*"
      maven:
        patterns:
          - "org.apache.maven.plugins:*"
    registries:
      - levigo-nexus
registries:
  levigo-nexus:
    type: maven-repository
    url: https://artifacts.jadice.com
    username: ${{ secrets.LEVIGO_NEXUS_USERNAME_RO }}
    password: ${{ secrets.LEVIGO_NEXUS_PASSWORD_RO }}
...
