name: Continuous Delivery

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.github/workflows/continuous-integration.yml'

env:
  # This will suppress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # `installAtEnd` and `deployAtEnd` are only effective with recent version of the corresponding plugins.
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  TAG_PREFIX: 'jadice-dss-utils-'

jobs:

  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      ## compute the string of the next version
      - name: Bump version and create tag
        id: semanticversion
        uses: StackAdapt/github-tag-action@c39fa6d65cd3def233513f21ba395a09dbc92eea # v7
        with:
          release_branches: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fetch_all_tags: true
          tag_prefix: ${{ env.TAG_PREFIX }}

      ## check if the computed string of the next version is conform to our regex
      - name: Verify and print new build number
        run: |
          if echo '${{ steps.semanticversion.outputs.new_tag }}' |grep -Eq '^${{ env.TAG_PREFIX }}[0-9]+[.][0-9]+[.][0-9]+$'; then
            echo Tag '${{ steps.semanticversion.outputs.new_tag }}', New version '${{ steps.semanticversion.outputs.new_version }}', Changelog '${{ steps.semanticversion.outputs.changelog }}'
          else
            echo 'unexpected tag format - aborting'
            exit -1
          fi

      - name: Set version and tag variables
        run: |
          echo "NEW_VERSION=${{ steps.semanticversion.outputs.new_version }}" >> $GITHUB_ENV \
          && echo "NEW_TAG=${{ env.TAG_PREFIX }}${{ steps.semanticversion.outputs.new_version }}" >> $GITHUB_ENV

      - name: Set up JDK
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'maven'

      - name: Prepare maven settings
        env:
          REPOSITORY_URL: ${{ secrets.LEVIGO_NEXUS_REPO_RELEASES }}
          REPOSITORY_USERID: ${{ secrets.PUB_NEXUS2_USERNAME }}
          REPOSITORY_CREDENTIALS: ${{ secrets.PUB_NEXUS2_PASSWORD }}
          REPOSITORY_RELEASE_USERID: ${{ secrets.PUB_NEXUS2_USERNAME_RW }}
          REPOSITORY_RELEASE_CREDENTIALS: ${{ secrets.PUB_NEXUS2_PASSWORD_RW }}
        run: |
          mkdir -p ~/.m2
          envsubst < ./.github/settings.xml > ~/.m2/settings.xml

      - name: Set version
        id: version
        run: |
          echo Releasing as ${{ env.NEW_VERSION }}
          mvn ${{ env.MAVEN_CLI_OPTS }} versions:set -DnewVersion=${{ env.NEW_VERSION }}

      - name: Perform build
        run: mvn -B verify -Dmaven.test.failure.ignore=true

      - name: Publish Test Report for JDK 11
        id: test-report
        uses: ScalableCapital/action-surefire-report@4004a71652495d6ed111f5b717c2cf9aa0f37627 # v2.0.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_test_failures: true
          check_name: Test Report for JDK 11

      - name: Deploy packages
        run: mvn ${{ env.MAVEN_CLI_OPTS }} deploy -Dmaven.install.skip=true

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64 # v3.0.3
        with:
          name: Release ${{ env.NEW_VERSION }}
          tag_name: ${{ steps.semanticversion.outputs.new_tag }}
          draft: false
          prerelease: false
          files: |
            ./target/jadice-dss-utils-${{ steps.semanticversion.outputs.new_version }}.jar
            ./target/jadice-dss-utils-${{ steps.semanticversion.outputs.new_version }}-javadoc.jar
            ./target/jadice-dss-utils-${{ steps.semanticversion.outputs.new_version }}-sources.jar

      - name: Notify developers
        uses: slackapi/slack-github-action@dcb1066f776dd043e64d0e8ba94ca15cc7e1875d # v4.0.0
        if: ${{ failure() && github.actor != 'dependabot[bot]' }}
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            channel: ci_docp
            username: "GitHub"
            text: Failed to release new version `${{ steps.semanticversion.outputs.new_version }}` of *${{ github.repository }}*
